- name: launch one nova instance
  connection: local
  hosts: localhost
  vars_files:
   - vars/copc_vars.yml

  tasks: 
 
  - name: Ensure New server is up. 
    nova_compute:
      state: present
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      login_username: "{{ lookup('env', 'OS_USERNAME') }}"
      login_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      login_tenant_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      name: demo-server
      image_id: "{{ coreos_image_id }}"
      key_name: "{{ keypair }}"
      flavor_id: 5 
      security_groups: "{{ security_group }}"
      floating_ip_pools:
      - "{{ floating_ip_pool }}"
      user_data: lookup("file", "files/coreos-init.sh")
    register: instance
